version: '3.8'

services:
  mysql-db-portofolio:
    image: mariadb:10.6
    container_name: mysql-db-inventory
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db-portofolio
      MYSQL_USER: kounet
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 11

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "9988:80"
    environment:
      PMA_HOST: mysql-db-portofolio
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  demo:
    build: ./demo
    container_name: demo
    ports:
      - '8098:8098'
    restart: always
    depends_on:
      - mysql-db-portofolio
    environment:
      # URL JDBC pour H2
      DB_URL: jdbc:h2:mem:db-portofolio;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: # H2
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_SHOW_SQL: true

  postgres-service:
    image: postgres
    container_name: postgres-service
    volumes:
      - postgres_data_kounet:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_kounet_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: k1234
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kounet@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-service:5432/keycloak_kounet_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: k1234
      KEYCLOAK_ADMIN: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres-service

  front:
    build: ./front/potofolio-react-app
    image: front
    container_name: front
    ports:
      - '82:80'

volumes:
  mysql_data:
  postgres_data_kounet:
  pgadmin_data:
